### PR TITLE
Split the classes into namespaces

### PR DESCRIPTION
**Pull request by leofeyer**
As discussed, this PR splits the PHP classes into namespaces.

### CODE REVIEW

**Comment by ausi** [comment]
Now that we have sub-namespaces, should we remove the prefixes of these classes and their interfaces?

* `Image/ImageDimensions` => `Image/Dimensions`
* `Picture/PictureConfiguration` => `Picture/Configuration`
* `Picture/PictureConfigurationItem` => `Picture/ConfigurationItem`
* `Picture/PictureGenerator` => `Picture/Generator`
* `Resize/ResizeCalculator` => `Resize/Calculator`
* `Resize/ResizeConfiguration` => `Resize/Configuration`
* `Resize/ResizeCoordinates` => `Resize/Coordinates`
* `Resize/ResizeOptions` => `Resize/Options`

This would make it more readable and shorter.

**Comment by leofeyer** [comment]
Probably yes, although

```php
$pictureConfig = new PictureConfiguration();
```

is more explicit than

```php
$pictureConfig = new Configuration();
```

There are a couple of classes named `Configuration` and removing the prefix might lead to issues such as:

```
use Contao\Image\Picture\Configuration as PictureConfiguration;
use Symfony\DependencyInjection\Configuration as SymfonyConfiguration;
```

So, after having written this, I think I prefer to keep the prefixes. 😄

**Comment by ausi** [comment]
But Symfony named it `Configuration` too.

And I think a shorter version of `Contao\Image\Picture\PictureConfigurationItemInterface` would be great.

Isn’t that the great benefit of namespaces that we don’t have to use class name prefixes?

**Comment by leofeyer** [comment]
Yes, but that only works if we do not have to use namespace aliases all the time. But there are no conflicts within the library, so it is your call. I will update the PR accordingly. 😄

**Comment by ausi** [comment]
> But there are no conflicts within the library, so it is your call.

@contao/developers opinions on https://github.com/contao/image/pull/3#issuecomment-235928738 ?

**Comment by aschempp** [comment]
I would not remove the prefixes for most things. As mentioned the name is more clear, otherwise people will just need to use aliases.

**Comment by discordier** [comment]
As long as the library itself has no conflicts, prefixes could (IMO should) be removed.
As soon as there are conflicts, they should (IMO must) be prevailed.

As we do not have collisions (something like `JpgConfiguration` and `SvgConfiguration` which would get moved to `Configuration` in their respective namespace and the like), I vote for removing them.

**Comment by leofeyer** [comment]
I have renamed the classes and instantly ran into issues:

```
PHP Fatal error:  Cannot use Contao\Image\Resize\Configuration as Configuration because the name is already in use in /Users/leofeyer/Sites/contao/image/tests/PictureGeneratorTest.php on line 18
```

Of course I can fix this by adding aliases, but then we might as well keep the longer names. 😄

**Comment by discordier** [comment]
Just out of curiosity, what was the other configuration class which was used in the namespace?

**Comment by leofeyer** [comment]
I have pushed the changes so you can see them here: https://github.com/contao/image/compare/feature/short-names?expand=1

I had to add quite a few aliases to make it work, so definitely -1 from me.

**Comment by ausi** [comment]
OK, convinced :) lets keep the prefixes.

**Comment by ausi** [comment]
I think I should move the Test classes also into sub-namspaces, right?

**Comment by ausi** [comment]
Now, while integrating the namespace changes into contao/core-bundle#342, I’m not so sure about `Contao\Image\Image\Image` anymore. How about leaving `Image`, `ImageDimensions` and `ImportantPart` in the root namespace and only use the sub-namespaces `Picture` and `Resize`?

**Comment by discordier** [comment]
`Contao\Image\Image\Image` certainly sounds strange, I agree it would be better located at `Contao\Image\Image`

**Pull request merged**
