### PR TITLE
Remove interfaces to improve flexibility for future changes

### PR DESCRIPTION
**Pull request by ausi**
I think creating an interface for every class in this library was a mistake. Every feature we added to the 1.0 beta version broke BC because interfaces had to be changed.

IMO we should keep the following interfaces:

- `ImageInterface`
- `DeferredImageInterface`
- `ResizerInterface`
- `DeferredResizerInterface`
- `DeferredImageStorageInterface`
- `PictureInterface`
- `PictureGeneratorInterface`

and remove these:

- `ImageDimensionsInterface`
- `ImportantPartInterface`
- `PictureConfigurationInterface`
- `PictureConfigurationItemInterface`
- `ResizeCalculatorInterface`
- `ResizeConfigurationInterface`
- `ResizeCoordinatesInterface`
- `ResizeOptionsInterface`

This would enable us to add more options and configurations in minor releases.

### CODE REVIEW

**Comment by leofeyer** [comment]
+1 for removing the interfaces in v1.0.

**Comment by ausi** [comment]
> I guess we should completely remove the interfaces then and not deprecate them.

I generally agree. I removed all of them except the `ResizeConfigurationInterface::MODE_*` constants because IMO it’s very likely that they get used.

**Comment by Toflar** [comment]
I don't quite understand that point of view. Sure, they might have been used - just like any other interface. That's the purpose of alpha versions (0.* versions), you don't have to guarantee BC so when you feel like you're ready to release the first stable version (1.0.0), you can release a clean library. So I don't see why we would need to distinguish here. Either break BC completely or not at all.

**Comment by leofeyer** [comment]
Fair point.

**Comment by ausi** [comment]
I think that the `ResizeConfigurationInterface::MODE_*` constants are special in this case. And because it is very easy to keep them (and without overhead because the interface file never gets loaded if not used) I don’t see a reason to break BC here.

**Comment by Toflar** [comment]
Personally, I would clean them up but as you're the one maintaining stuff, I'll leave it up to you.

**Comment by BugBuster1701** [comment]
When updating a 4.8.RC1 installation:

- Updating contao/image (1.0.0-beta3 => 1.0.0-beta4)

`PHP Warning:  Declaration of Contao\CoreBundle\Image\LegacyResizer::executeResize(Contao\Image\ImageInterface $image, Contao\Image\ResizeCoordinatesInterface $coordinates, string $path, Contao\Image\ResizeOptionsInterface $options): Contao\Image\ImageInterface 
            should be compatible with Contao\Image\DeferredResizer::executeResize(Contao\Image\ImageInterface $image, Contao\Image\ResizeCoordinates $coordinates, string $path, Contao\Image\ResizeOptions $options): Contao\Image\ImageInterface in vendor/contao/core-bundle/src/Image/LegacyResizer.php on line 31
`

`PHP Warning:  Uncaught ReflectionException: Class Contao\Image\ResizeCoordinatesInterface not found in vendor/contao/core-bundle/src/Image/LegacyResizer.php:31`

`PHP Fatal error:  Declaration of Contao\CoreBundle\Image\LegacyResizer::resize(Contao\Image\ImageInterface $image, Contao\Image\ResizeConfigurationInterface $config, Contao\Image\ResizeOptionsInterface $options): Contao\Image\ImageInterface must be compatible with Contao\Image\Resizer::resize(Contao\Image\ImageInterface $image, Contao\Image\ResizeConfiguration $config, Contao\Image\ResizeOptions $options): Contao\Image\ImageInterface in vendor/contao/core-bundle/src/Image/LegacyResizer.php on line 31
`

Do I have to update to 4.8.RC2 now to make the installation work again?

**Comment by Toflar** [comment]
That sounds like the PHP 7.2.20/7.3.7 issue.

**Comment by leofeyer** [comment]
> Do I have to update to 4.8.RC2 now to make the installation work again?

Yes, you have. Contao 4.8.0-RC1 is not compatible with contao/image 1.0.0-beta4.

**Comment by ausi** [comment]
> Do I have to update to 4.8.RC2 now to make the installation work again?

You could also add a conflict for `1.0.0-beta4` or require `1.0.0-beta3` explicitly, but updating to `4.8.0-RC2` is the way to go here I think.

**Comment by BugBuster1701** [comment]
"conflict" was my first step. Now i have make the update to RC2.

**Pull request merged**
