### PR TITLE
Convert images to RGB and strip metadata

### LINKED ISSUE #34: Remove EXIF data and convert to RGB by default
I think thumbnails do not need any EXIF data and should never be in any other color space than RGB. This would make the thumbnails a lot smaller :-)

### PR DESCRIPTION
**Pull request by ausi**
Fixes #34

Blocked on contao/imagine-svg#7 and avalanche123/Imagine#564.

### CODE REVIEW

**Comment by aschempp** [comment]
does that work with all implementations? Or will we get an exception e.g. when using GD?

**Comment by ausi** [comment]
Yes, it works with all Imagine implementations. In GD `strip()` and `usePalette()` just do nothing, because GD strips always and converts always to RGB.

**Comment by leofeyer** [comment]
It seems that the GDlib does not handle palette conversions very well:

http://stackoverflow.com/questions/12815305/bad-cmyk-to-rgb-conversion-with-gd

Therefore, do we really need this step?

**Comment by ausi** [comment]
With GD, the behavior before and after this pull request is exactly the same, see https://github.com/contao/image/pull/37#issuecomment-302001706

But with Gmagick and Imagick, the image is converted to RGB and profiles and metadata get stripped from the image.

We can make the conversion to RGB configurable, I’m not sure if `strip()` should be configurable too.

**Comment by leofeyer** [comment]
> With GD, the behavior before and after this pull request is exactly the same,

Ok, sorry for not reading thoroughly. Then we do not need this to be configurable I think.

**Comment by ausi** [comment]
> The only problem I see here is that resizer settings should be considered in the cache key.

If we don’t make them configurable, they are not “settings” I think and are not needed in the cache key then because they can’t change.

**Comment by Toflar** [comment]
Fine with me then :) I think I'll only test it on a real life project once the avalanche123/Imagine#564 discussion has found an end, ok?

**Comment by ausi** [comment]
I think you can test on real life project already. It looks like the issue from avalanche123/Imagine#564 was related to my installation of ImageMagick because the delegate `lcms` was missing. You can test that on your system by calling `convert -list configure | grep DELEGATES` and if `lcms` shows up, everything should be fine.

**Pull request merged**
