### PR TITLE
Add method to reset the DeferredImageStorageFilesystem

### PR DESCRIPTION
**Pull request by aschempp**
see https://github.com/contao/contao/pull/1105

### CODE REVIEW

**Comment by aschempp** [comment]
Absolutely. First of all, the method can obviously be there without the interface. Also, the `kernel.reset` tag is not related to the interface at all, except that auto-wiring would automatically add the reset call. But we're not using auto-wiring anyway.

We _could_ rename the method to something like `releaseAllLocks` and call that in the core bundle…

**Comment by Toflar** [comment]
Ah, I thought maybe the services resetter checks the interface as well but it does not indeed. We could still require `symfony/contracts` and implement it. That's exactly why there's `symfony/contracts` but I don't mind either way.

**Comment by aschempp** [comment]
> Ah, I thought maybe the services resetter checks the interface as well but it does not indeed. We could still require `symfony/contracts` and implement it. That's exactly why there's `symfony/contracts` but I don't mind either way.

I think we should not, as `contao/image` is currently supported in Symfony 2.8+, where the contracts don't exist yet.

**Comment by leofeyer** [comment]
Can this PR be closed now that #1105 has been merged?

**Comment by ausi** [comment]
I don’t think we should add a `reset()` or `releaseAllLocks()` method here as it would be against the purpose of the class.

If we want to ensure that no locks are active, we could add a `hasLocks()` method and throw an exception in Contao if it returns `true` (which should never happen because all locks should be immediately released after use).

I would prefer to leave it as is, because if a lock gets retrieved twice we would throw an exception anyway.

**Pull request closed without merging**
